# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  name: 'MyAgentPool'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'         # or pin e.g. 8.0.404
    includePreview: false

- script: dotnet --info
  displayName: 'Dotnet info (sanity check)'

- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build --configuration Release --no-restore
  displayName: 'dotnet build Release'
